#pragma config(Sensor, S1,     sound,          sensorNone)
#pragma config(Motor,  motorA,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int clapcount = 0;

	while(true)
	{
		resetMotorEncoder(right);

		while(SensorValue(sound) < 50)
		{

		}



		if(time1[T1] < 1000)
		{
			while(getMotorEncoder(motorA) < 180)
			{
				motor[right] = 30;

			}

			motor[right] = 0;

		}


		clapcount = clapcount + 1;

		clearTimer(T1);


		while(SensorValue(sound) > 45)
		{

		}








	}

}
